### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by ashtongraves** [leq382121/SpoTube#1]
![image](https://user-images.githubusercontent.com/8889507/48305119-a7977000-e4ea-11e8-9b4e-f6e39f317a9c.png)
Received this error when trying out program with verified correct login. Also receiving this notice in Electron 
![image](https://user-images.githubusercontent.com/8889507/48305160-53d95680-e4eb-11e8-9ec1-8cc2073719cd.png)

**Comment by ChuckyG** [comment]
I looked around at this myself today.  It appears the script uses Electron, Nightmare, and Daydream node packages, so after uninstalling those and upgrading to the latest versions of all three, I still ended up with the same notice. I'm guessing Electron is the issue here as that's what emulates the browser.

**Comment by leq382121** [comment]
@ashtongraves @ChuckyG Hey guys sorry for late reply. Yes, I have just tested and I was able to replicate problem aswell. Will take a look on this when getting some free time. Probably i will have to use some other technology to emulate the browser or see what can i do in this case. Thanks for letting know!

**Comment by leq382121** [comment]
@ashtongraves @ChuckyG Problem is solved. Code just got too old, since spotify changed their UI. Now it's fixed. Happy downloading. 👍

**Comment by ChuckyG** [comment]
Thanks, I checked it out and it's working again.  No idea why it keeps coming up and complaining about browser versions, but apparently it'll work regardless of that.

**Comment by leq382121** [comment]
@ChuckyG In any case, since Electron uses Chromium, It will be able to handle all the things that Chrome browser is capable of.
